name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run tests
      run: |
        for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do
          if [ -f "$dir/Cargo.toml" ]; then
            echo "Running tests in $dir"
            (cd "$dir" && cargo test --verbose)
          fi
        done
